require: 
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot

AllCops:
  TargetRubyVersion: 3.2
  # RuboCop has a bunch of cops enabled by default. This setting tells RuboCop
  # to ignore them, so only the ones explicitly set in this file are enabled.
  DisabledByDefault: true
  Exclude:
    - '**/templates/**/*'
    - '**/vendor/**/*'
    - 'spec/dummy/**/**/*'
    - 'actionpack/lib/action_dispatch/journey/parser.rb'
    - 'bin/*'
    - 'Rakefile'

Style/Documentation:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: true

Lint/AssignmentInCondition:
  Enabled: false

Lint/BigDecimalNew:
  Enabled: false

Lint/HeredocMethodCallPosition:
  Enabled: true

Lint/NestedMethodDefinition:
  Enabled: true

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: true

Layout/LineLength:
  Max: 100

Style/AndOr:
  Enabled: true

Layout/CommentIndentation:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  Enabled: true

Layout/EmptyLinesAroundMethodBody:
  Enabled: true

Layout/EmptyLinesAroundModuleBody:
  Enabled: true

Layout/EndAlignment:
  Enabled: true
  AutoCorrect: true
  EnforcedStyleAlignWith: variable

Style/HashSyntax:
  Enabled: true
  EnforcedShorthandSyntax: always

Layout/IndentationWidth:
  Enabled: true

Layout/SpaceAfterColon:
  Enabled: true

Layout/SpaceAroundKeyword:
  Enabled: true

Style/MethodDefParentheses:
  Enabled: true

Layout/SpaceInsideParens:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/ExtraSpacing:
  Enabled: true
  AllowForAlignment: false
  AllowBeforeTrailingComments: false
  ForceEqualSignAlignment: false

Layout/IndentationStyle:
  Enabled: true

Style/RedundantSelf:
  Enabled: true

Style/RedundantPercentQ:
  Enabled: true

Lint/RequireParentheses:
  Enabled: true

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: no_space

Layout/FirstParameterIndentation:
  EnforcedStyle: align_parentheses

Style/NumericPredicate:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/ExponentialNotation:
  Enabled: false

Style/Encoding:
  Enabled: true

Layout/EmptyLineAfterMagicComment:
  Enabled: true

Style/NumericLiterals:
  Enabled: true

Style/EndlessMethod:
  Enabled: true
  EnforcedStyle: allow_single_line

Layout/AccessModifierIndentation:
  Enabled: true

Layout/HashAlignment:
  Enabled: true
  EnforcedColonStyle: key
  EnforcedLastArgumentHashStyle: always_inspect

Layout/ParameterAlignment:
  Enabled: true
  EnforcedStyle: with_first_parameter

Layout/BlockAlignment:
  Enabled: true
  EnforcedStyleAlignWith: start_of_block

Layout/CaseIndentation:
  Enabled: true

Layout/ClosingParenthesisIndentation:
  Enabled: true

Layout/DotPosition:
  EnforcedStyle: leading

Layout/EmptyLineBetweenDefs:
  Enabled: true

Layout/EmptyLines:
  Enabled: true

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/EmptyLinesAroundAccessModifier:
  Enabled: true

Layout/EmptyLinesAroundBlockBody:
  Enabled: true

Layout/FirstArrayElementLineBreak:
  Enabled: true

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/HeredocArgumentClosingParenthesis:
  Enabled: true

Layout/FirstArgumentIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/IndentationConsistency:
  Enabled: true

Layout/LeadingCommentSpace:
  Enabled: true

Layout/MultilineArrayLineBreaks:
  Enabled: true

Layout/MultilineBlockLayout:
  Enabled: true

Layout/MultilineHashBraceLayout:
  Enabled: true

Layout/MultilineHashKeyLineBreaks:
  Enabled: true

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true

Layout/MultilineMethodCallBraceLayout:
  Enabled: true

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  Enabled: true

Layout/RescueEnsureAlignment:
  Enabled: false

Layout/SpaceAfterComma:
  Enabled: true

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: true

Layout/SpaceAroundOperators:
  Enabled: true

Layout/SpaceBeforeBlockBraces:
  Enabled: true

Layout/SpaceBeforeFirstArg:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: true
  EnforcedStyle: space

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: no_space

Layout/SpaceInLambdaLiteral:
  Enabled: true
  SupportedStyles:
    - require_no_space

Layout/TrailingEmptyLines:
  Enabled: true
  SupportedStyles:
    - final_newline

Layout/TrailingWhitespace:
  Enabled: true

Layout/ArgumentAlignment:
  Enabled: true
  EnforcedStyle: with_first_argument

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: true
  Max: 50
  Exclude:
    - 'db/migrate/**/*'

Metrics/BlockLength:
  Enabled: false

